pipewire &
pipewire-pulse &
wireplumber &

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

dunst &
udiskie &
playerctld daemon &
picom &
feh --no-fehbg --bg-scale '/home/chuck/Pictures/triangle-mountain.png' &
sct 4000 &
dwmblocks &

# lockscreen settings
xset s noblank &
xset s 300 &
xss-lock slock &

mpv --no-video ~/.local/share/sounds/custom/windows95.m4a &

exec ssh-agent dbus-run-session dwm
