#!/bin/sh

. ~/.local/bin/blocks/color_themes/onedark

[[ $BLOCK_BUTTON -eq 6 ]] && $TERMINAL -e $EDITOR "$0"

IM=$( awk '{print $1}' /proc/loadavg )

FG=$black
BG=$white

(( $(echo "$IM > 5" |bc -l) )) && BG=$red && FG=$black

printf "^b$BG^^c$FG^  ^c$BG^^b$FG^ $IM"
