#!/bin/sh

case $BLOCK_BUTTON in
    3) playerctl play-pause ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

WHT="#ebdbb2"
BLC="#282828"
GRN="#1ed760"

FG=$WHT
BG=$BLC
ICON=""

#DATA=$(playerctl metadata --format '{{ trunc(default( title , "-" ), 14) }}' 2>/dev/null || printf "Nothing to play") 
DATA=$(playerctl metadata --format "{{emoji(status)}} {{title}}" 2>/dev/null || echo "Nothing to play")

playerctl metadata 2>/dev/null | grep -iq spotify && FG=$BLC && BG=$GRN && ICON="" 

echo "^c$FG^^b$BG^ $ICON $DATA ^d^"
#scrollepoch "^c$FG^^b$BG^ $ICON $DATA ^d^"
