#!/bin/bash

export SWWW_TRANSITION=grow
export SWWW_TRANSITION_POS=bottom
export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_DURATION=2

case $1 in
    period-changed)
        if [[ "$3" = "night" ]]; then
            /home/chuck/scripts/settheme.sh "$3"
        elif [[ "$3" = "daytime" ]]; then
            /home/chuck/scripts/settheme.sh "$3"
        fi
    ;;
esac
