#!/bin/sh

export SWWW_TRANSITION=grow
export SWWW_TRANSITION_POS=bottom
export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_DURATION=2

case $1 in
    period-changed)
        /home/chuck/.local/bin/settheme.sh "$3"
    ;;
esac
