#!/bin/sh

export SWWW_TRANSITION=grow
export SWWW_TRANSITION_POS=bottom
export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_DURATION=2

case $1 in
    period-changed)
        swww img ~/Pictures/flowerboy-"$3".jpg

        /home/chuck/.local/bin/settheme.sh "$3"
        # case $3 in
        #     night)
        #         exec swww img ~/Pictures/flowerboy-night.jpg
        #         ;;
        #     daytime)
        #         exec swww img ~/Pictures/flowerboy.jpg
        #         ;;
        # esac
    ;;
esac
