# xorg lockscreen
xset s on &
xset s 300 &
xss-lock i3lock &

# statusbar
dwmblocks &

# bluelight filter
gammastep -m randr &

# tray applets
nm-applet --indicator &
blueman-applet &

# keyboard daemon
~/.config/systemd/user/hotkeys.sh &

# notification daemon
dunst &

# music daemon
playerctld daemon &

# wallpaper
xwallpaper --stretch ~/Pictures/flowerboy.jpg &

# polkit agent
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

exec dwm
